-- This is cic3 VHDL model
-- Generated by initentity script
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
USE std.textio.all;


ENTITY cic3 IS
    PORT( A : IN  STD_LOGIC;
          Z : OUT STD_LOGIC
        );
END cic3;

ARCHITECTURE rtl OF cic3 IS
BEGIN
    buf:PROCESS(A)
    BEGIN
        Z<=A;
    END PROCESS;
END ARCHITECTURE;
